name: Build and Publish ASP.NET MVC App

on:
  push:
    branches: [main]  # Or your default branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.0  # Or 7.0.x depending on your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Publish
      run: dotnet publish -c Release -o published

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mvc-app
        path: published
